server:
  port: 9094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
  config:
    import: "optional:configserver:http://localhost:9091"

management:
  tracing:
    sampling:
      probability: 1.0